# This is a basic workflow to help you get started with Actions

name: CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ubuntu:
    strategy:
      matrix:
        platform: [x86, x64]
        os: [ubuntu-18.04, ubuntu-20.04, ubuntu-latest]
    runs-on: '${{ matrix.os }}'
    name: 'Test: ${{ matrix.os }} / ${{ matrix.platform }}'
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up GCC
        uses: ./
        with:
          platform: '${{ matrix.platform }}'
          cc: 1
      - name: Build foo.exe
        uses: gcc 
